name: build-and-test.yml
on: [push]
jobs:
  build-and-test-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
        continue-on-error: [false]
    continue-on-error: ${{ matrix.continue-on-error }}
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Setup NodeJS environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Go environment
        uses: actions/setup-go@v2
      - name: Run Go tests using Mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: vtest
      - name: Build backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v buildAll
      - name: Install frontend tools
        run: |
          npm install -g yarn
          yarn install
      - name: List all Yarn packages
        run: |
          yarn list
      - name: Build frontend
        run: |
          yarn build
